# Video Notes

## Loops

In [8]:
countdown = 5
while countdown > 0:
   b     print(countdown, end= " ")
        countdown -= 1
print('Blast off!')

5 4 3 2 1 Blast off!


In [9]:
countdown = 5
for x in range(countdown, 0, -1):
    print(x)
print('Blast off!')

5
4
3
2
1
Blast off!


In [10]:
row = int(input("enter an interger: "))

while row >= 0:
        j = 0
        while j <= row:
            print(j, end = ' ')
            j += 1
        print("")
        row -= 1
        
        

enter an interger: 9
0 1 2 3 4 5 6 7 8 9 
0 1 2 3 4 5 6 7 8 
0 1 2 3 4 5 6 7 
0 1 2 3 4 5 6 
0 1 2 3 4 5 
0 1 2 3 4 
0 1 2 3 
0 1 2 
0 1 
0 


In [11]:
row = int(input("enter an interger: "))

for x in range(row, -1, -1):
    for j in range(x + 1):
        print(j, end= ' ')
    print('')

enter an interger: 9
0 1 2 3 4 5 6 7 8 9 
0 1 2 3 4 5 6 7 8 
0 1 2 3 4 5 6 7 
0 1 2 3 4 5 6 
0 1 2 3 4 5 
0 1 2 3 4 
0 1 2 3 
0 1 2 
0 1 
0 


In [15]:
x = input("Enter your name: ")

for char in x:
    if char.lower() not in "aeiou":
        print(char, end= ' ')
    
    

Enter your name: oscar
s c r 

In [17]:
x = ['Paul', 'Bill', 'Kay']

for name in x:
    print(name + ', as himself')

Paul, as himself
Bill, as himself
Kay, as himself


## Loop Exists

Example: test if x is prime

In [21]:
# testing the for loop
x = int(input("Enter a number: "))
flag_prime = True

for i in range(2, x):
        # check if i devides x
        if x % i == 0:
            # now I know x is not prime
            flag_prime = False

if flag_prime == True:
    print(x, "is prime")
else:
    print(x, "is not prime")

Enter a number: 41
41 is prime


We want to have a better algorithm by stoping as soon as the number can be divided by a number different than itself

In [30]:
# testing an algorithm that requires less computation
x = int(input("Enter a number: "))
flag_prime = True

i = 2  # first prime number
while i < x and flag_prime:
        # check if i devides x
        if x % i == 0:
            # now I know x is not prime
            flag_prime = False
            print('last checked number was', i)
        i += 1

if flag_prime == True:
    print(x, "is prime")
else:
    print(x, "is not prime")

Enter a number: 21
last checked number was 3
21 is not prime


In [59]:
# using break to reduce unneccessary computations
x = int(input("Enter a number: "))
# flag_prime = True

for i in range(2, x):
        # check if i devides x
        if x % i == 0:
            print(x, "is not prime")
            break
else:  # occurs when the for loop ends normaly
    print(x, "is prime")


Enter a number: 6
6 is not prime


Example: are the vowels in a word in Alphabetical order

In [70]:
# testing break again
word = input("Enter a word: ")
last_letter = 'a'

for letter in word.lower():
    if letter in 'aeiou':
        print(letter)
        # check to see if order is alphabetical
        if letter < last_letter:
            print("The vowels in", word, "are out of order.")
            break
        last_letter = letter
else: 
    print("The vowels in", word, "are in order.")
            

Enter a word: Paul
a
u
The vowels in Paul are in order.


In [77]:
# using continue
word = input("Enter a word: ")
last_letter = 'a'

for letter in word.lower():
    if letter not in 'aeiou': ## if letter not in aeiuo we continue to next iteam
        continue  # works as a filterb
    # check to see if order is alphabetical
    if letter < last_letter:
        print("The vowels in", word, "are out of order.")
        break
    last_letter = letter
else: 
    print("The vowels in", word, "are in order.")
            

Enter a word: Oscar
The vowels in Oscar are out of order.


## Algorithms

Algorithm:
1. Abstract set of steps a program will execute
2. Plan for solving a problem

Problem: How do you find the square root of x, where x > 0 and belongs to the set of real numbers. We want to be withoin epsilon of the real square root.

In [90]:
# Exhaustive Search (aka brute force algo)
x = float(input('Enter a number:'))
num_iterations = 0
epsilon = 0.00001  # max margin of error
ans = 0.0

while ans ** 2 <= x:
    ans += epsilon
    num_iterations += 1

print(ans, "is close to the square root of", x)
print('Number of iterations:', num_iterations)



Enter a number:9
3.000000000011186 is close to the square root of 9.0
Number of iterations: 300000


In [111]:
# Bisection Search
# only applies to numbers equal or greater than 1 
# because the square root of decimals is greater than itself

x = float(input('Enter a number:'))
num_iterations = 0
epsilon = 0.00001  # max margin of error
low_bound = 0
up_bound = x
ans = (up_bound + low_bound) /2

while (up_bound - low_bound) >= 2 * epsilon:
    print("lower bound: ", low_bound, end= ' ')
    print("upper bound: ", up_bound)
    num_iterations += 1
    if ans ** 2 < x:  # bisetrix is less than square root
        low_bound = ans  # then adjust lower bound
    else:
        up_bound = ans  # else adjust upper bound
    ans = (up_bound + low_bound) /2 

print(ans, "is close to the square root of", x)
print("Number of iterations: ", num_iterations)

Enter a number:9
lower bound:  0 upper bound:  9.0
lower bound:  0 upper bound:  4.5
lower bound:  2.25 upper bound:  4.5
lower bound:  2.25 upper bound:  3.375
lower bound:  2.8125 upper bound:  3.375
lower bound:  2.8125 upper bound:  3.09375
lower bound:  2.953125 upper bound:  3.09375
lower bound:  2.953125 upper bound:  3.0234375
lower bound:  2.98828125 upper bound:  3.0234375
lower bound:  2.98828125 upper bound:  3.005859375
lower bound:  2.9970703125 upper bound:  3.005859375
lower bound:  2.9970703125 upper bound:  3.00146484375
lower bound:  2.999267578125 upper bound:  3.00146484375
lower bound:  2.999267578125 upper bound:  3.0003662109375
lower bound:  2.99981689453125 upper bound:  3.0003662109375
lower bound:  2.99981689453125 upper bound:  3.000091552734375
lower bound:  2.9999542236328125 upper bound:  3.000091552734375
lower bound:  2.9999542236328125 upper bound:  3.0000228881835938
lower bound:  2.999988555908203 upper bound:  3.0000228881835938
2.999997138977051 i

### Heron's Method

Let ans be any real number greater or equal to 1.
Let ans be our first guess.
Consider the value x /ans. 
For any x /ans, ans * (x /ans) = x.
Thus:
1. If x /ans = ans, then ans^2 = x (ans is the square root of x)
2. If x /ans > ans, then ans^2 < x (we need a bigger ans).
3. If x /ans < ans, then ans^2 > x (we need a smaller ans). 

Also, note that the answer must be between ans and x /ans.

Note that Newton's Method is a generalized form of Heron's method.

Let f(ans) = ans^2 - x
fin ans such that f(ans) = 0

In [110]:
x = float(input('Enter a number:'))

epsilon = 0.00001
num_iterations = 0

ans = 1  # first guest

while abs(x/ ans - ans) > 2 * epsilon:  # keep shortening the testing interval
    ans = (x/ans + ans) /2  #  pick the bisectrix until x /ans is close to ans
    num_iterations += 1
    
print(ans, "is close to the square root of", x)
print('Number of iterations: ', num_iterations)

Enter a number:9
3.000000001396984 is close to the square root of 9.0
Number of iterations:  5


## Arrays

Array are not native to python. They are available through numpy.

Array are optimized for computational performance.

Arrays are sequences, so they share properties and methods with other python sequence objects.

Array have limited range of operations, when compared to lists for example.

All items in the array need to be the same type.

In [113]:
import numpy as np

In [115]:
x = np.arange(0, 20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [116]:
x[2] = 22
x

array([ 0,  1, 22,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [119]:
x.dtype

dtype('int64')

In [120]:
x[10] = 'shoe'

ValueError: invalid literal for int() with base 10: 'shoe'

In [121]:
x.append(3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [122]:
x.pop()

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [123]:
np.random.rand(5,5)

array([[0.03804032, 0.45712938, 0.40388224, 0.4388878 , 0.35186093],
       [0.65479068, 0.25178812, 0.72353058, 0.61794241, 0.22566228],
       [0.49196855, 0.01350938, 0.0629544 , 0.74933313, 0.88854389],
       [0.63886183, 0.51643828, 0.27009726, 0.93079399, 0.7606518 ],
       [0.21758759, 0.7955673 , 0.91638226, 0.65985611, 0.74362995]])

In [145]:
ar = np.random.randn(30)  # standard normal dist m= 0, std = 1
ar

array([ 0.41677819, -0.88857182,  0.31842667,  1.49776706, -1.6771778 ,
        2.56852871, -0.26591379,  1.10611933,  0.82764138, -0.77737969,
        1.36990179, -0.74404947,  1.71023612, -0.08737278, -0.7604338 ,
        0.14168674,  1.50887393, -0.94480754, -0.58766616,  2.12722914,
        2.43754594,  0.59137295, -0.40006316, -0.57262374, -0.34670597,
       -1.13234747,  0.01342887, -0.11001021, -0.19882449, -0.78681396])

In [146]:
ar.mean()

0.21182583265427618

In [147]:
ar.std()

1.1076880614518396

In [150]:
ar = ar.reshape(6,5)
ar

array([[ 0.41677819, -0.88857182,  0.31842667,  1.49776706, -1.6771778 ],
       [ 2.56852871, -0.26591379,  1.10611933,  0.82764138, -0.77737969],
       [ 1.36990179, -0.74404947,  1.71023612, -0.08737278, -0.7604338 ],
       [ 0.14168674,  1.50887393, -0.94480754, -0.58766616,  2.12722914],
       [ 2.43754594,  0.59137295, -0.40006316, -0.57262374, -0.34670597],
       [-1.13234747,  0.01342887, -0.11001021, -0.19882449, -0.78681396]])

In [151]:
ar.mean(axis = 0)  # mean of each column

array([ 0.96701565,  0.03585678,  0.27998354,  0.14648688, -0.37021368])

In [152]:
ar.mean(axis = 1)  # mean of each rowb

array([-0.06655554,  0.69179919,  0.29765637,  0.44906322,  0.3419052 ,
       -0.44291345])

## Comprehensions

In [156]:
squares = []
for i in range(1,11):
    squares.append(i**2)

    
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [157]:
[i**2 for i in range(1, 11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [159]:
[(row, column) for row in range(4) for column in range(4)]

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3)]

In [161]:
# get ordered list of letters in a word
import string
word = input("Enter a word: ")
# string.ascii_lowercase all the abecedary in order

letters = [l for l in string.ascii_lowercase if l in word]

print(letters)

Enter a word: oscar
['a', 'c', 'o', 'r', 's']


In [163]:
# get letter frequency dictionary

text = "Here is some example text."
freque = { letter: text.count(letter) for letter in text }
print(freque)

{'H': 1, 'e': 6, 'r': 1, ' ': 4, 'i': 1, 's': 2, 'o': 1, 'm': 2, 'x': 2, 'a': 1, 'p': 1, 'l': 1, 't': 2, '.': 1}


# Book exercises: Chapter 4

4.1 Assign the value 7 to the variable guess_me. Then, write the conditional tests (if, else, and elif) to print the string 'too low' if guess_me is less than 7, 'too high' if greater than 7, and 'just right' if equal to 7.

In [1]:
guess_me = 7

if guess_me < 7:
    print('too low')
elif guess_me > 7:
    print('too high')
else:
    print('just right')

just right


4.2 Assign the value 7 to the variable guess_me and the value 1 to the variable start. Write a while loop that compares start with guess_me. Print too low if start is less than guess me. If start equals guess_me, print 'found it!' and exit the loop. If start is greater than guess_me, print 'oops' and exit the loop. Increment start at the end of the loop.

In [15]:
guess_me = int(input('Enter an integer:'))
start = 1

while True:  # indefinite loop as the ending is determined by the if clauses below
    print('Number:', start, end= ' ')
    if start > guess_me:  # put the break options first in the list to reduce iterations
        print('opps')
        break
    elif start == guess_me:
        print('found it!')
        break
    else:
        print('too low')
        
    start += 1

Enter an integer:8
Number: 1 too low
Number: 2 too low
Number: 3 too low
Number: 4 too low
Number: 5 too low
Number: 6 too low
Number: 7 too low
Number: 8 found it!


4.3 Use a for loop to print the values of the list [3, 2, 1, 0].

In [16]:
for i in [3, 2, 1, 0]:
    print(i)

3
2
1
0


4.4 Use a list comprehension to make a list of the even numbers in range(10).

In [35]:
even_num_ls = [n for n in range(10) if n % 2 == 0]
print(even_num_ls)

[0, 2, 4, 6, 8]


4.5 Use a dictionary comprehension to create the dictionary squares. Use range(10) to return the keys, and use the square of each key as its value.

In [31]:
squares_dc = { n:n**2 for n in range(10) }
print(squares_dc)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


4.6 Use a set comprehension to create the set odd from the odd numbers in range(10).

In [36]:
odds_st = { n for n in range(10) if n % 2 != 0}
print(odds_st)

{1, 3, 5, 7, 9}
