# Video lecture notes

In [2]:
import numpy as np

In [2]:
class Drone:
    power_system = 'battery'
    def fly(self):
        return "the %s powered drone is flying" % (self.power_system)

d = Drone()

* class call to define an object
* self to self-reference the object
* methods can be defined inside an object using def
* always create an instance by connecting a variable to the object

In [4]:
def drone_flyer(drone):
    print(drone.fly())

In [5]:
drone_flyer(d)

the battery powered drone is flying


In [6]:
d.power_system = "Subway - Eat Fresh"

In [7]:
drone_flyer(d)

the Subway - Eat Fresh powered drone is flying


Note that we are runing the same function with the same input but the output of the function is not constant. This violets the core of functional programing.

This paradigm happens beacuse in object-oriented programming, objects are mutable.

In [10]:
# Exploring mapping
x = range(0, 10)
x

range(0, 10)

In [12]:
def cube(num):
    return num ** 3


In [13]:
cube(2)

8

In [14]:
# create a new list of every value in a range, cubed
new_list = []
x_gn = range(0,15)
for item in x_gn:
    new_list.append(cube(item))

In [15]:
new_list

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744]

In [16]:
# creating the empty list is unnecessary 
map_list = map(cube, x_gn)

In [20]:
type(map_list)

map

In [18]:
print(list(map_list))

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744]


Note that the map_list value is inmutable

In [21]:
print(list(map_list))

[]


The generator was used already

**Lazy evaluation:** Until we need the value, the program will store the value until we need it. Hence the map_list object is a generator and not a list.

## Filters

In [23]:
def even(num):
    return num % 2 == 0

In [24]:
even(4)

True

In [25]:
even(5)

False

In [26]:
list(map(even, x_gn))

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True]

In [27]:
list(filter(even, x_gn))

[0, 2, 4, 6, 8, 10, 12, 14]

Filter works as map but filters-out items that do not meet the logic in the applied function

In [33]:
list(map(even, x_gn))

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True]

In [34]:
map_store_test = list(map(even, x_gn))

In [42]:
test_list = [
    'hello',
    'x,y,z. i like this.',
    'this is two xx',
    'this, x, here x us, here it is againx'
]

In [43]:
def has_2x(my_string):
    return my_string.count('x') >= 2

In [44]:
has_2x('hello')

False

In [45]:
has_2x('xx hello')

True

In [46]:
list(filter(has_2x, test_list))

['this is two xx', 'this, x, here x us, here it is againx']

In [52]:
def to_caps(my_string):
    return my_string.capitalize()

In [53]:
list(map(to_caps, filter(has_2x, test_list)))

['This is two xx', 'This, x, here x us, here it is againx']

## List comprehensions

In [54]:
x = range(0,10)

In [56]:
[item ** 3 for item in x]

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [57]:
[item * 2 for item in x if item % 3 == 0]

[0, 6, 12, 18]

In [58]:
[float(item) for item in x]

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [59]:
def cube_if(num):
    if num % 3 == 0:
        return num * 3
    else:
        return num * 2

In [60]:
[cube_if(i) for i in x]

[0, 2, 4, 9, 8, 10, 18, 14, 16, 27]

In [61]:
list(map(cube_if, x))

[0, 2, 4, 9, 8, 10, 18, 14, 16, 27]

## Lambda functions

In [62]:
[ item ** 2 for item in x ]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [63]:
def square(num):
    return num**2

In [64]:
[square(i) for i in x]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [66]:
list(map(square, x))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [67]:
list(map(lambda i: i **2, x))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [68]:
square_lambda = lambda i: i ** 2

In [69]:
list(map(square_lambda, x))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [70]:
type(square_lambda)

function

In [71]:
type(square)

function

In [79]:
list(filter(lambda z: z % 2 == 0, range(1, 20)))

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [77]:
list(map(lambda j: j ** 2, filter(lambda z: z % 2 == 0, range(1, 20))))

[4, 16, 36, 64, 100, 144, 196, 256, 324]

In [83]:
my_range = range(1,20)
output = []
for z in my_range:
    if z % 2 ==0:
        output.append(z **2)

In [84]:
output

[4, 16, 36, 64, 100, 144, 196, 256, 324]

## NumPy

In [20]:
a = np.arange(20)

In [5]:
a.mean()

4.5

In [6]:
a.max()

9

In [7]:
a.min()

0

In [8]:
a.std()

2.8722813232690143

### Vectorization

In [9]:
%timeit [x*x for x in a]

3.28 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
%timeit a*a

548 ns ± 35.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


NumPy is vectorized. So when a * a, instead of a multiplying every value in a, a does a vector multiplication on itself

### Boolean selection

In [14]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [13]:
np.array(list(map(lambda x: x % 2 == 0, a)))

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [11]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [15]:
np2 = np.arange(20000)

In [17]:
%timeit [x for x in np2 if x % 2 == 0]

11.5 ms ± 229 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%timeit np2[np2 % 2 == 0]

315 µs ± 31.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
a[ (a > 15) | (a < 5)]

array([ 0,  1,  2,  3,  4, 16, 17, 18, 19])

In [26]:
npa = np.arange(25)
print(npa)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [23]:
print(type(npa))

<class 'numpy.ndarray'>


In [24]:
npa.dtype

dtype('int64')

In [25]:
np.float64(npa)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [27]:
b = np.array(range(20))

In [28]:
b.dtype

dtype('int64')

In [29]:
np.array([1.0,0,2,3]).dtype

dtype('float64')

In [30]:
np.array([True, 2, 2.0]).dtype

dtype('float64')

Note that np arrays can have multiple data types

In [32]:
np.array([True, 2, 2.0], dtype = 'uint')

array([1, 2, 2], dtype=uint64)

In [33]:
npa.size

25

In [34]:
npa.shape

(25,)

In [35]:
npa.argmin()

0

In [36]:
npa.argmax()

24

In [37]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [40]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
np.linspace(0,10,11).astype('int')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
ar = np.linspace(0,10,11)

In [44]:
ar

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
ar[0] = np.nan

In [46]:
ar

array([nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
ar.min(), ar.max(), ar.mean()

(nan, nan, nan)

### Vectorization and Multidimensional Arrays

In [56]:
np.random.seed(20)

In [51]:
npa = np.random.randint(0, 50, 20)

In [52]:
npa

array([27, 16, 42, 35, 44, 38,  3, 46, 34, 33, 18, 14,  8, 12, 39, 46, 37,
       49,  7, 17])

In [53]:
npa * 2

array([54, 32, 84, 70, 88, 76,  6, 92, 68, 66, 36, 28, 16, 24, 78, 92, 74,
       98, 14, 34])

In [54]:
npa ** 3

array([ 19683,   4096,  74088,  42875,  85184,  54872,     27,  97336,
        39304,  35937,   5832,   2744,    512,   1728,  59319,  97336,
        50653, 117649,    343,   4913])

In [55]:
npa ** 2 ** 3

array([  282429536481,     4294967296,  9682651996416,  2251875390625,
       14048223625216,  4347792138496,           6561, 20047612231936,
        1785793904896,  1406408618241,    11019960576,     1475789056,
             16777216,      429981696,  5352009260481, 20047612231936,
        3512479453921, 33232930569601,        5764801,     6975757441])

In [57]:
def transformation(val):
    return (val*2) - 1

In [58]:
transformation(3)

5

In [59]:
transformation(npa)

array([53, 31, 83, 69, 87, 75,  5, 91, 67, 65, 35, 27, 15, 23, 77, 91, 73,
       97, 13, 33])

In [64]:
transform_2 = np.vectorize(transformation)

In [65]:
transform_2(npa)

array([53, 31, 83, 69, 87, 75,  5, 91, 67, 65, 35, 27, 15, 23, 77, 91, 73,
       97, 13, 33])

In [66]:
%timeit [transformation(x) for x in npa]

16 µs ± 465 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [67]:
%timeit transform_2(npa)

20.8 µs ± 893 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [68]:
npa = np.arange(25)

In [69]:
print(npa)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [70]:
npa2 = npa.reshape((5,5))

In [71]:
print(npa2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [72]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [73]:
np.zeros(npa2.shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
npa2.shape

(5, 5)

In [75]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [77]:
np.random.seed(10)

In [86]:
npa2 = np.random.randint(1,10,25).reshape(5,5)
npa2

array([[2, 3, 6, 1, 2],
       [1, 2, 1, 3, 2],
       [2, 1, 1, 6, 1],
       [5, 7, 7, 1, 3],
       [4, 4, 3, 7, 1]])

In [91]:
npa3 = np.random.randint(1,10,25).reshape(5,5)
npa3

array([[1, 4, 5, 5, 7],
       [9, 5, 3, 2, 2],
       [7, 4, 5, 6, 5],
       [1, 3, 9, 1, 8],
       [7, 6, 9, 3, 3]])

In [92]:
# testing random seed
print(np2.mean())
print(np3.mean())

5.84
6.0


In [93]:
npa * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [94]:
npa2 < npa3

array([[False,  True, False,  True,  True],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False,  True],
       [False, False,  True, False,  True],
       [ True,  True,  True, False,  True]])

In [95]:
(npa2 < npa3).sum()

16

In [96]:
npa3.min()

1

In [99]:
npa3.max(axis=0)  # max value per column

array([9, 6, 9, 6, 8])

In [97]:
npa3.max(axis=1)  # max value per row

array([7, 9, 7, 9, 9])

In [100]:
npa2.transpose()

array([[2, 1, 2, 5, 4],
       [3, 2, 1, 7, 4],
       [6, 1, 1, 7, 3],
       [1, 3, 6, 1, 7],
       [2, 2, 1, 3, 1]])

In [102]:
npa2.T

array([[2, 1, 2, 5, 4],
       [3, 2, 1, 7, 4],
       [6, 1, 1, 7, 3],
       [1, 3, 6, 1, 7],
       [2, 2, 1, 3, 1]])

In [103]:
npa2 * npa3

array([[ 2, 12, 30,  5, 14],
       [ 9, 10,  3,  6,  4],
       [14,  4,  5, 36,  5],
       [ 5, 21, 63,  1, 24],
       [28, 24, 27, 21,  3]])

In [104]:
print(npa2.shape)
print(npa3.shape)

(5, 5)
(5, 5)


### Flattening arrays

In [108]:
np2 = npa2.flatten()
np2

array([2, 3, 6, 1, 2, 1, 2, 1, 3, 2, 2, 1, 1, 6, 1, 5, 7, 7, 1, 3, 4, 4,
       3, 7, 1])

In [109]:
np2[0] = 25

In [111]:
np2

array([25,  3,  6,  1,  2,  1,  2,  1,  3,  2,  2,  1,  1,  6,  1,  5,  7,
        7,  1,  3,  4,  4,  3,  7,  1])

In [110]:
npa2

array([[2, 3, 6, 1, 2],
       [1, 2, 1, 3, 2],
       [2, 1, 1, 6, 1],
       [5, 7, 7, 1, 3],
       [4, 4, 3, 7, 1]])

Note that flatten creates a copy of the orginal array, thus the values in the orginal array do not change if values in the second array are mutated

In [141]:
np4 = np.random.randint(0,30,30).reshape(5,6)

In [142]:
np4

array([[ 1, 12, 11, 29, 28,  5],
       [15, 20, 21, 20,  3, 14],
       [14, 13, 20, 20, 17,  1],
       [ 2,  1,  1,  2, 12, 12],
       [18, 14, 13,  2,  5, 24]])

In [143]:
raveled = np4.ravel()

In [144]:
raveled

array([ 1, 12, 11, 29, 28,  5, 15, 20, 21, 20,  3, 14, 14, 13, 20, 20, 17,
        1,  2,  1,  1,  2, 12, 12, 18, 14, 13,  2,  5, 24])

In [145]:
raveled[0] = 99

In [146]:
np4

array([[99, 12, 11, 29, 28,  5],
       [15, 20, 21, 20,  3, 14],
       [14, 13, 20, 20, 17,  1],
       [ 2,  1,  1,  2, 12, 12],
       [18, 14, 13,  2,  5, 24]])

In [147]:
np2.cumsum()

array([25, 28, 34, 35, 37, 38, 40, 41, 44, 46, 48, 49, 50, 56, 57, 62, 69,
       76, 77, 80, 84, 88, 91, 98, 99])

In [148]:
np2.cumprod()

array([         25,          75,         450,         450,         900,
               900,        1800,        1800,        5400,       10800,
             21600,       21600,       21600,      129600,      129600,
            648000,     4536000,    31752000,    31752000,    95256000,
         381024000,  1524096000,  4572288000, 32006016000, 32006016000])

In [149]:
np2

array([25,  3,  6,  1,  2,  1,  2,  1,  3,  2,  2,  1,  1,  6,  1,  5,  7,
        7,  1,  3,  4,  4,  3,  7,  1])

In [150]:
np.random.seed(10)

In [151]:
ar = np.arange(12)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [156]:
ar2 = np.random.randint(0, 12, 12).reshape(3,4)
ar2

array([[ 6,  7,  8, 11],
       [10,  8,  9,  2],
       [ 0,  6,  7,  8]])

In [157]:
ar[0]

0

In [159]:
ar[2:8:2]

array([2, 4, 6])

In [160]:
ar[-1:-8:-2]

array([11,  9,  7,  5])

In [161]:
ar2[:,1:3]

array([[7, 8],
       [8, 9],
       [6, 7]])

In [162]:
ar2[1:3, :]

array([[10,  8,  9,  2],
       [ 0,  6,  7,  8]])

In [163]:
ar2[::2, ::2]

array([[6, 8],
       [0, 7]])

In [164]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [165]:
ar2

array([[ 6,  7,  8, 11],
       [10,  8,  9,  2],
       [ 0,  6,  7,  8]])

In [166]:
ar2.flatten()

array([ 6,  7,  8, 11, 10,  8,  9,  2,  0,  6,  7,  8])

In [167]:
np.vstack([ar, ar2.flatten()])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8, 11, 10,  8,  9,  2,  0,  6,  7,  8]])

In [169]:
ar.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [171]:
ar2

array([[ 6,  7,  8, 11],
       [10,  8,  9,  2],
       [ 0,  6,  7,  8]])

In [176]:
np.vstack((ar.reshape(3,4), ar2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  7,  8, 11],
       [10,  8,  9,  2],
       [ 0,  6,  7,  8]])

In [168]:
np.hstack([ar, ar2.flatten()])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  7,  8, 11, 10,
        8,  9,  2,  0,  6,  7,  8])

In [177]:
np.hstack((ar.reshape(3,4), ar2))

array([[ 0,  1,  2,  3,  6,  7,  8, 11],
       [ 4,  5,  6,  7, 10,  8,  9,  2],
       [ 8,  9, 10, 11,  0,  6,  7,  8]])

In [178]:
np.hstack((ar.reshape(3,4), ar2)).shape

(3, 8)

In [181]:
np.vstack([ar for x in range(10)])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [182]:
np.concatenate((ar, ar2.flatten()))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  7,  8, 11, 10,
        8,  9,  2,  0,  6,  7,  8])

In [184]:
np.concatenate(([ar], [ar2.flatten()]), axis=1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  7,  8, 11,
        10,  8,  9,  2,  0,  6,  7,  8]])

In [186]:
ar2

array([[ 6,  7,  8, 11],
       [10,  8,  9,  2],
       [ 0,  6,  7,  8]])

In [185]:
np.dstack([ar2, ar2])

array([[[ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [11, 11]],

       [[10, 10],
        [ 8,  8],
        [ 9,  9],
        [ 2,  2]],

       [[ 0,  0],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8]]])

In [194]:
ar3 = np.dstack([ar2, ar2])
ar3

array([[[ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [11, 11]],

       [[10, 10],
        [ 8,  8],
        [ 9,  9],
        [ 2,  2]],

       [[ 0,  0],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8]]])

In [196]:
np.dsplit(ar3, 2)

[array([[[ 6],
         [ 7],
         [ 8],
         [11]],
 
        [[10],
         [ 8],
         [ 9],
         [ 2]],
 
        [[ 0],
         [ 6],
         [ 7],
         [ 8]]]), array([[[ 6],
         [ 7],
         [ 8],
         [11]],
 
        [[10],
         [ 8],
         [ 9],
         [ 2]],
 
        [[ 0],
         [ 6],
         [ 7],
         [ 8]]])]

In [195]:
ar21, ar22 = np.dsplit(ar3, 2)

In [192]:
ar21

array([[[ 6],
        [ 7],
        [ 8],
        [11]],

       [[10],
        [ 8],
        [ 9],
        [ 2]],

       [[ 0],
        [ 6],
        [ 7],
        [ 8]]])

In [193]:
ar22

array([[[ 6],
        [ 7],
        [ 8],
        [11]],

       [[10],
        [ 8],
        [ 9],
        [ 2]],

       [[ 0],
        [ 6],
        [ 7],
        [ 8]]])

In [198]:
ar21.reshape(3,4)  # original ar2

array([[ 6,  7,  8, 11],
       [10,  8,  9,  2],
       [ 0,  6,  7,  8]])

In [201]:
np.dsplit(ar3, 2)

[array([[[ 6],
         [ 7],
         [ 8],
         [11]],
 
        [[10],
         [ 8],
         [ 9],
         [ 2]],
 
        [[ 0],
         [ 6],
         [ 7],
         [ 8]]]), array([[[ 6],
         [ 7],
         [ 8],
         [11]],
 
        [[10],
         [ 8],
         [ 9],
         [ 2]],
 
        [[ 0],
         [ 6],
         [ 7],
         [ 8]]])]

In [200]:
np.dsplit(ar3, 2)[0]

array([[[ 6],
        [ 7],
        [ 8],
        [11]],

       [[10],
        [ 8],
        [ 9],
        [ 2]],

       [[ 0],
        [ 6],
        [ 7],
        [ 8]]])

In [203]:
np.squeeze(np.dsplit(ar3, 2)[0])  # original ar2 matrix

array([[ 6,  7,  8, 11],
       [10,  8,  9,  2],
       [ 0,  6,  7,  8]])

In [211]:
ar2

array([[ 6,  7,  8, 11],
       [10,  8,  9,  2],
       [ 0,  6,  7,  8]])

In [204]:
np.hsplit(ar2,2)

[array([[ 6,  7],
        [10,  8],
        [ 0,  6]]), array([[ 8, 11],
        [ 9,  2],
        [ 7,  8]])]

In [205]:
np.hsplit(ar2,2)[0]

array([[ 6,  7],
       [10,  8],
       [ 0,  6]])

In [206]:
np.hsplit(ar2,2)[1]

array([[ 8, 11],
       [ 9,  2],
       [ 7,  8]])

In [208]:
np.vsplit(ar2.T,2)[1]

array([[ 8,  9,  7],
       [11,  2,  8]])

In [212]:
np.vsplit(ar2,3)

[array([[ 6,  7,  8, 11]]), array([[10,  8,  9,  2]]), array([[0, 6, 7, 8]])]